//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSTempoWasm.i10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSTempoWasm.i10n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Down.
        /// </summary>
        internal static string BUTTON_ADJUST_DOWN {
            get {
                return ResourceManager.GetString("BUTTON_ADJUST_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Up.
        /// </summary>
        internal static string BUTTON_ADJUST_UP {
            get {
                return ResourceManager.GetString("BUTTON_ADJUST_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        internal static string BUTTON_BEAT {
            get {
                return ResourceManager.GetString("BUTTON_BEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Metric.
        /// </summary>
        internal static string BUTTON_DOWNLOAD_METRIC {
            get {
                return ResourceManager.GetString("BUTTON_DOWNLOAD_METRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebase.
        /// </summary>
        internal static string BUTTON_REBASE {
            get {
                return ResourceManager.GetString("BUTTON_REBASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string BUTTON_RESET {
            get {
                return ResourceManager.GetString("BUTTON_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test  Beat.
        /// </summary>
        internal static string BUTTON_TEST_BEAT {
            get {
                return ResourceManager.GetString("BUTTON_TEST_BEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible Beat.
        /// </summary>
        internal static string LABEL_AUDIBLE_BEAT {
            get {
                return ResourceManager.GetString("LABEL_AUDIBLE_BEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average (10/15/20):.
        /// </summary>
        internal static string LABEL_AVERAGE {
            get {
                return ResourceManager.GetString("LABEL_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:.
        /// </summary>
        internal static string LABEL_BEAT_AVERAGE {
            get {
                return ResourceManager.GetString("LABEL_BEAT_AVERAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM Interval:.
        /// </summary>
        internal static string LABEL_BEAT_BPM_INTERVAL {
            get {
                return ResourceManager.GetString("LABEL_BEAT_BPM_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Count.
        /// </summary>
        internal static string LABEL_BEAT_COUNT {
            get {
                return ResourceManager.GetString("LABEL_BEAT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last:.
        /// </summary>
        internal static string LABEL_BEAT_LAST {
            get {
                return ResourceManager.GetString("LABEL_BEAT_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM.
        /// </summary>
        internal static string LABEL_BPM {
            get {
                return ResourceManager.GetString("LABEL_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string LABEL_ELAPSED {
            get {
                return ResourceManager.GetString("LABEL_ELAPSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jitter.
        /// </summary>
        internal static string LABEL_JITTER {
            get {
                return ResourceManager.GetString("LABEL_JITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability.
        /// </summary>
        internal static string LABEL_STABILITY {
            get {
                return ResourceManager.GetString("LABEL_STABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/hsaito/HSTempoWasm/blob/master/CHANGELOG.md.
        /// </summary>
        internal static string LOCATION_CHANGELOG {
            get {
                return ResourceManager.GetString("LOCATION_CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/hsaito/HSTempoWasm/blob/master/HELP.md.
        /// </summary>
        internal static string LOCATION_HELP {
            get {
                return ResourceManager.GetString("LOCATION_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MENU_ABOUT {
            get {
                return ResourceManager.GetString("MENU_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MENU_HOME {
            get {
                return ResourceManager.GetString("MENU_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/4.
        /// </summary>
        internal static string METER_2_4 {
            get {
                return ResourceManager.GetString("METER_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3/4.
        /// </summary>
        internal static string METER_3_4 {
            get {
                return ResourceManager.GetString("METER_3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4/4.
        /// </summary>
        internal static string METER_4_4 {
            get {
                return ResourceManager.GetString("METER_4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBI.
        /// </summary>
        internal static string METER_VBI {
            get {
                return ResourceManager.GetString("METER_VBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string TEXT_CHANGELOG {
            get {
                return ResourceManager.GetString("TEXT_CHANGELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refer to the help  for more information..
        /// </summary>
        internal static string TEXT_HELP_HOWTO {
            get {
                return ResourceManager.GetString("TEXT_HELP_HOWTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various factors may affect accuracy of the measurement. Do not rely on this system for mission critical applications. The HSTempoWasm developers are not responsible for any damages caused by use of this system..
        /// </summary>
        internal static string TEXT_WARNING_ACCURACY {
            get {
                return ResourceManager.GetString("TEXT_WARNING_ACCURACY", resourceCulture);
            }
        }
    }
}
