//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSTempoWasm.i10n {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HSTempoWasm.i10n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BUTTON_BEAT {
            get {
                return ResourceManager.GetString("BUTTON_BEAT", resourceCulture);
            }
        }
        
        internal static string BUTTON_RESET {
            get {
                return ResourceManager.GetString("BUTTON_RESET", resourceCulture);
            }
        }
        
        internal static string LABEL_STABILITY {
            get {
                return ResourceManager.GetString("LABEL_STABILITY", resourceCulture);
            }
        }
        
        internal static string LABEL_BPM {
            get {
                return ResourceManager.GetString("LABEL_BPM", resourceCulture);
            }
        }
        
        internal static string LABEL_AUDIBLE_BEAT {
            get {
                return ResourceManager.GetString("LABEL_AUDIBLE_BEAT", resourceCulture);
            }
        }
        
        internal static string BUTTON_TEST_BEAT {
            get {
                return ResourceManager.GetString("BUTTON_TEST_BEAT", resourceCulture);
            }
        }
        
        internal static string BUTTON_DOWNLOAD_METRIC {
            get {
                return ResourceManager.GetString("BUTTON_DOWNLOAD_METRIC", resourceCulture);
            }
        }
        
        internal static string BUTTON_ADJUST_UP {
            get {
                return ResourceManager.GetString("BUTTON_ADJUST_UP", resourceCulture);
            }
        }
        
        internal static string BUTTON_ADJUST_DOWN {
            get {
                return ResourceManager.GetString("BUTTON_ADJUST_DOWN", resourceCulture);
            }
        }
        
        internal static string BUTTON_REBASE {
            get {
                return ResourceManager.GetString("BUTTON_REBASE", resourceCulture);
            }
        }
        
        internal static string METER_VBI {
            get {
                return ResourceManager.GetString("METER_VBI", resourceCulture);
            }
        }
        
        internal static string METER_2_4 {
            get {
                return ResourceManager.GetString("METER_2_4", resourceCulture);
            }
        }
        
        internal static string METER_3_4 {
            get {
                return ResourceManager.GetString("METER_3_4", resourceCulture);
            }
        }
        
        internal static string METER_4_4 {
            get {
                return ResourceManager.GetString("METER_4_4", resourceCulture);
            }
        }
        
        internal static string LABEL_ELAPSED {
            get {
                return ResourceManager.GetString("LABEL_ELAPSED", resourceCulture);
            }
        }
        
        internal static string LABEL_BEAT_COUNT {
            get {
                return ResourceManager.GetString("LABEL_BEAT_COUNT", resourceCulture);
            }
        }
        
        internal static string LABEL_AVERAGE {
            get {
                return ResourceManager.GetString("LABEL_AVERAGE", resourceCulture);
            }
        }
        
        internal static string LABEL_LAST {
            get {
                return ResourceManager.GetString("LABEL_LAST", resourceCulture);
            }
        }
        
        internal static string LABEL_BEAT_AVERAGE {
            get {
                return ResourceManager.GetString("LABEL_BEAT_AVERAGE", resourceCulture);
            }
        }
        
        internal static string LABEL_BEAT_BPM_INTERVAL {
            get {
                return ResourceManager.GetString("LABEL_BEAT_BPM_INTERVAL", resourceCulture);
            }
        }
        
        internal static string TEXT_WARNING_ACCURACY {
            get {
                return ResourceManager.GetString("TEXT_WARNING_ACCURACY", resourceCulture);
            }
        }
        
        internal static string LOCATION_HELP {
            get {
                return ResourceManager.GetString("LOCATION_HELP", resourceCulture);
            }
        }
        
        internal static string LOCATION_CHANGELOG {
            get {
                return ResourceManager.GetString("LOCATION_CHANGELOG", resourceCulture);
            }
        }
        
        internal static string TEXT_CHANGELOG {
            get {
                return ResourceManager.GetString("TEXT_CHANGELOG", resourceCulture);
            }
        }
        
        internal static string TEXT_HELP_HOWTO {
            get {
                return ResourceManager.GetString("TEXT_HELP_HOWTO", resourceCulture);
            }
        }
    }
}
